### ISSUE TITLE
Simulate Pan-tilt motion in vrep using Matlab

### ISSUE THREAD

**Issue by ktiwari9** [victorgan/corke2011robotics#1]
Hi there, 
I am quite new to VRep . i want to use to use Peter Corke Robotics toolbox in Matlab and simulate a pan-tilt motion for a camera/kinect in Vrep.
Could you please provide some advise / pseudo code as how to control the camera motion in vrep using commands from matlab ?
Any help is greatly appreciated.

**Comment by victorgan** [comment]
I'm not the creator this codebase; it's a fork of Peter Corke's Robotic Toolbox - perhaps try directing any questions there.
